### ISSUE TITLE
Can't install the Symfony CLI (anymore) with shivammathur/setup-php GitHub action

### ISSUE THREAD

**Issue by Kocal** [symfony-cli/symfony-cli#105]
For reference: https://github.com/shivammathur/setup-php/issues/568

Hi!

Since some minutes/hours, we are not able to setup and use the Symfony CLI with https://github.com/shivammathur/setup-php with the following step: 

```yaml
        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: 8.0
              tools: symfony-cli 

```

Does something changed on the APT repository (https://repo.symfony.com/apt/)?

Thanks!
