### ISSUE TITLE
Generated ELASTICSEARCH_URL seems to lack necessary trailing slash

### ISSUE THREAD

**Issue by gothick** [symfony-cli/symfony-cli#154]
I'm using what seems to be the default config from the FriendsOfSymfony [Elastica bundle recipe](https://github.com/symfony/recipes-contrib/blob/main/friendsofsymfony/elastica-bundle/5.0/config/packages/fos_elastica.yaml):

```
# .../config/packages/fos_elastica.yaml
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
```

I'd expected this to work with the Docker automatic config, but it seems that although the public port (8856) is picked up correctly from my docker config, the ELASTICSEARCH_URL that's generated is `ELASTICSEARCH_URL=http://127.0.0.1:8856` (I see this with `symfony var:export --multiline`.)

Unfortunately, it seems that fos_elastica expects the URL to have a trailing slash. With the above config, every request gives me a "Malformed URL" HttpException. If I manually change the url to exactly `http://127.0.0.1:8856/`, with the trailing slash, everything works fine.

I've worked around it by switching the config to use the host and port variables that symfony-cli also successfully sets up:

```
fos_elastica:
    clients:
        default:
            host: '%env(ELASTICSEARCH_HOST)%'
            port: '%env(ELASTICSEARCH_PORT)%'
```

...and adding defaults for them to my .env, so I still end up pointed to http://localhost:9200/ by default in other, non-Docker/symfony-cli environments. (It also works if I change my config to `default: { url: '%env(ELASTICSEARCH_URL)%/' }`, of course.)

There seem to be a few moving parts here, and I'm not sure I'm not missing something, but it feels to me like the generated URL should have the trailing slash if the config generated by adding fos_elastica requires it? (Or is ELASTICSEARCH_URL not specifically targeted at that bundle?) Any insight appreciated!
