### ISSUE TITLE
Demo - Upgrade npm to latest version

### ISSUE THREAD

**Issue by flovntp** [symfony-cli/symfony-cli#214]
Hi, 

I just try to deploy Symfony demo right now and get this warning during `symfony deploy`
```
          W: npm notice 
          W: npm notice New patch version of npm available! 8.19.2 -> 8.19.3
          W: npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.19.3
          W: npm notice Run npm install -g npm@8.19.3 to update!
```

To solve it, i needed to add this dependencies into .platform.app.yaml to ensure using latest npm version: 
```
dependencies:
    php:
        composer/composer: "^2"
    nodejs:
        npm: latest
```

my 2 cents
