### ISSUE TITLE
Allow configuring Docker compose to automatically start with server

### ISSUE THREAD

**Issue by jmsche** [symfony-cli/symfony-cli#240]
Hi,

I think it would be nice to have an option (in .symfony.local.yaml?) to specify that it should also run Docker compose automatically when running the server.

Maybe also allowing to define the Docker compose files to use?
Like this:

```yaml
docker_compose:
    - docker-compose.yaml
    - docker-compose.override.yaml
```

So when running `server:start` it would run `docker compose up`? And if daemon is enabled with adding the `-d` option? (so when running `server:stop` it should also run `docker compose stop` if daemon was enabled)

**Comment by mwansinck** [comment]
This can already be achieved, we currently use this in some of our projects;

```yaml
# .symfony.local.yaml
workers:
  # built-in command that builds and watches front-end assets
  # yarn_encore_watch:
  #     cmd: ['yarn', 'encore', 'dev', '--watch']
  yarn_encore_watch: ~

  docker_compose_up:
    cmd: ['docker-compose', 'up']
```

when `symfony server:start` is executed, `docker-compose up` is started as worker, when the proces is stopped, it stops all the workers, including `docker-compose up`. This also works when `symfony server:start` is running as daemon with `-d`

**Comment by tucksaun** [comment]
@mwansinck that was indeed the start of the reflexion during a chat we had with @jmsche

but I was concerned by the fact that it could cause issues with some workers being started too early (before docker compose up) and as such they could not start properly making server:start fail.
Did you experience anything similar?

**Comment by mwansinck** [comment]
> @mwansinck that was indeed the start of the reflexion during a chat we had with @jmsche
> 
> but I was concerned by the fact that it could cause issues with some workers being started too early (before docker compose up) and as such they could not start properly making server:start fail. Did you experience anything similar?

@tucksaun We do not yet have experience with that situation, but currently we are transforming our "old" docker development stacks to Symfony cli + docker, so I expected to have some experience within a few days :-)

Maybe if this will be an issue, a delay start will solve this; something like `sleep 5 && symfony console messenger:consume async`

**Comment by mwansinck** [comment]
@tucksaun I have tested the combination of messenger:consume and docker compose up, and the messenger:consume is failing due to starting to early. For now I have created the following workaround;

#bin/messenger_consume.sh
```bash
#!/bin/bash

# Wait to rabbitmq and other containers to start
sleep 15

symfony console messenger:consume async
```

# .symfony.local.yaml
```yaml
workers:
  # built-in command that builds and watches front-end assets
  # yarn_encore_watch:
  #     cmd: ['yarn', 'encore', 'dev', '--watch']
  yarn_encore_watch: ~

  docker_compose_up:
    cmd: ['docker-compose', 'up']

  messenger_consume_async:
    cmd: [ "bin/messenger_consume.sh" ]
    watch: [ "config", "src", "templates", "vendor" ]
````

The solution could be improved, possible by using the Docker API to check if the required / all container(s) are running.
