### ISSUE TITLE
Allow to have a CLI specific php.ini

### ISSUE THREAD

**Issue by yguedidi** [symfony-cli/symfony-cli#247]
It's already possible to define a custom php.ini per project.
But this one is used for all SAPI, and in my case there are some CLI command where I need `memory_limit=-1`.

Would be great to be able to configure that once for all :)

**Comment by tucksaun** [comment]
used for `symfony php`,  `symfony console` or  `symfony composer`?

**Comment by maciekpaprocki** [comment]
I could maybe take a look at that next. I guess we would want to have separate php.ini for different "channels" which would probably have to be in YAML. Something like:

```yaml
php.ini:
    -   file: php.ini
        channels: [ 'console', 'server' ]
    -   file: php-2.ini
        channels: [ 'php', 'composer', 'console' ]
```

If two of the ini files would be assigned this same channel then we would merge them in right order. 

Does that make sense?
