### ISSUE TITLE
CLI v5.5 does not create the proper env var for MongoDB

### ISSUE THREAD

**Issue by tgalopin** [symfony-cli/symfony-cli#272]
When using MongoDB with the following docker-compose.yaml:

```
version: '2.4'

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
```

When I use the Symfony CLI in 5.4, there is no URL automatically generated:

```
symfony var:export --multiline

 INFO  A new Symfony CLI version is available (5.5.0, currently running 5.4.17).

       If you installed the Symfony CLI via a package manager, updates are going to be automatic.
       If not, upgrade by downloading the new version at https://github.com/symfony-cli/symfony-cli/releases
       And replace the current binary (symfony) by the new one.

export MONGO_DATABASE=
export MONGO_HOST=127.0.0.1
export MONGO_NAME=
export MONGO_PASSWORD=
export MONGO_PORT=27017
export MONGO_SCHEME=mongodb
export MONGO_SERVER=mongodb://127.0.0.1:27017
export MONGO_USER=
export MONGO_USERNAME=
```

Thus I added in my env file: `MONGODB_URL="mongodb://root:pass@%env(MONGODB_HOST)%:%env(MONGODB_PORT)%/"` to have it available for my app while still using the autogenerated vars from Symfony CLI.

When I use Symfony CLI 5.5, the URL is now generated automatically (great!), but it's invalid:

```
export MONGO_URL=mongodb://:@127.0.0.1:27017/?authSource=
```

It's missing the username/password and I'm not certain why authSource is needed.
