### ISSUE TITLE
Version ^5.6.0 takes 25secs to get to php entry when used in combination with mysql docker

### ISSUE THREAD

**Issue by esserj** [symfony-cli/symfony-cli#363]
I upgraded through brew yesterday evening to 5.6.0, after that application response times went through the drain.
Below is for an empty index.php on php 8.1

version 5.6.0
<img width="396" alt="image" src="https://github.com/symfony-cli/symfony-cli/assets/1032205/75695c8d-1113-4ef2-8eb8-cbd26bb0b312">

version 5.5.10
<img width="390" alt="image" src="https://github.com/symfony-cli/symfony-cli/assets/1032205/8be10365-c400-4df0-9543-0563b7d9c484">

Downgrading to 5.5.10 solved the issue

System: Apple M1 Pro - Sonoma 14.0 (23A344)

**Comment by weaverryan** [comment]
Is it better in the latest version? Some mac tweaks were attempted in #361

**Comment by esserj** [comment]
Hi, thanks for looking into this.

There is some improvement, but load times are still high

<img width="383" alt="image" src="https://github.com/symfony-cli/symfony-cli/assets/1032205/438a833b-049c-4fee-bd79-d0a6e8272de3">

**Comment by shyim** [comment]
Do you have any VPN service running?

**Comment by esserj** [comment]
No VPN services active.

**Comment by esserj** [comment]
@shyim @weaverryan I've updated to 5.7.0 and have no issues anymore

**Comment by esserj** [comment]
I'll leave a reference compose configuration here just in case it can help:
```yaml
version: '3.8'

services:
    database:
        image: mysql:8.0
        ports:
            - '127.0.0.1:19306:3306'
        environment:
            MYSQL_DATABASE: somedb
            MYSQL_ROOT_PASSWORD: 111!!!!11!!!!111!!!!111!!!
```
