### ISSUE TITLE
Missing environment variables

### ISSUE THREAD

**Issue by OskarStark** [symfony-cli/symfony-cli#377]
I have the following simple docker-compose file:
```yaml
version: "3.9"

services:
    mongodb_primary:
        image: mongo:7-jammy
        environment:
            MONGO_INITDB_ROOT_USERNAME: primary
            MONGO_INITDB_ROOT_PASSWORD: password
        ports: [ '27017' ]

    mongodb_secondary:
        image: mongo:7-jammy
        environment:
            MONGO_INITDB_ROOT_USERNAME: secondary
            MONGO_INITDB_ROOT_PASSWORD: password
        ports: [ '27018' ]
```

and the result is:
```terminal
$ symfony var:export --multiline

export MONGODB_PRIMARY_DATABASE=
export MONGODB_PRIMARY_DB=
export MONGODB_PRIMARY_HOST=127.0.0.1
export MONGODB_PRIMARY_NAME=
export MONGODB_PRIMARY_PASSWORD=password
export MONGODB_PRIMARY_PORT=63663
export MONGODB_PRIMARY_SCHEME=mongodb
export MONGODB_PRIMARY_SERVER=mongodb://127.0.0.1:63663
export MONGODB_PRIMARY_URL=mongodb://primary:password@127.0.0.1:63663/?authSource=
export MONGODB_PRIMARY_USER=primary
export MONGODB_PRIMARY_USERNAME=primary
export MONGODB_SECONDARY_HOST=127.0.0.1
export MONGODB_SECONDARY_IP=127.0.0.1
export MONGODB_SECONDARY_PORT=63664
export SYMFONY_DOCKER_ENV=1
export SYMFONY_TUNNEL=
export SYMFONY_TUNNEL_BRAND=Platform.sh
export SYMFONY_TUNNEL_ENV=
```

However, as you can see, a lot of `MONGODB_SECONDARY_*` environment variables are missing.

The version I am using:
`Symfony CLI version 5.6.2 (c) 2021-2023 Fabien Potencier #StandWithUkraine (2023-10-25T14:07:11Z - stable)`
