### ISSUE TITLE
project:init command generates bad services.yaml

### ISSUE THREAD

**Issue by tomas-civinity** [symfony-cli/symfony-cli#401]
Not sure how it decides what services I needed (maybe looked at my `docker-compose.yml`), but the `.platform/services.yaml` is missing newlines after each service.

This is what I got:
```yaml

db:
    type: mysql:11.0elasticsearch:
    type: elasticsearch:7.9rabbitmq:
    type: rabbitmq:3.12redis:
    type: redis:7.2
```

This is what I would have expected:
```yaml
db:
    type: mysql:11.0
elasticsearch:
    type: elasticsearch:7.9
rabbitmq:
    type: rabbitmq:3.12
redis:
    type: redis:7.2
```
