### ISSUE TITLE
Add support for SIGTERM and/or SIGSTOP

### ISSUE THREAD

**Issue by zulus** [symfony-cli/symfony-cli#402]
Currently if I put `yarn dev-server` into `.symfony.local.yaml`, after `server:stop` dev-server process remain in background due way how it was spawned. 

CLI could send SIGTERM/SIGSTOP before SIGKILL, so process will be able to stop his childrens

**Comment by ellmout** [comment]
Hi,
Same problem with ``npm run watch``
When i CONTROL+C on ``symfony server:start``, i got :
<img width="386" alt="image" src="https://github.com/symfony-cli/symfony-cli/assets/4562782/802b97c0-a4ad-4848-a288-706aae1455cd">
i have to ``kill -9 pid``
if i run ``npm run watch`` and CONTROL+C, it stops correctly

I'm running Symfony CLI 5.7.8

**Comment by sarim** [comment]
@zulus @ellmout What operating system you guys are using? I'm in ubuntu and yarn stops correctly for me with symfony server:stop.

**Comment by ellmout** [comment]
> @zulus @ellmout What operating system you guys are using? I'm in ubuntu and yarn stops correctly for me with symfony server:stop.

Mac OS X

**Comment by Nihilus118** [comment]
For me it is working aswell on WSL2 Debian using a worker to call npm.

**Comment by Nihilus118** [comment]
I was finally able to reproduce the issue and fixed it by sending a SIGINT to the process group and give it a timeout of 5 seconds before killing the process.
If you have go installed you can just clone and `go install ` the branch to try it out @zulus @ellmout.

**Comment by zulus** [comment]
Thank You @Nihilus118 works fine for me. Tested on Sonoma (aarch64)

**Comment by zulus** [comment]
I made more tests and also other problems disappear. Shutdown is now **instant**! I don't have to wait and no longer see  `Shutting down! Waiting for all workers to be done.` with `Time out detected during "Worker docker" process exit`. So also docker containers correctly disappear

Good job! 

I have to integrate SF CLI with Eclipse PDT :P

**Comment by yguedidi** [comment]
@zulus so I guess this fixes also #398? 🙂

**Comment by zulus** [comment]
> @zulus so I guess this fixes also #398? 🙂

Yes, no timeouts, docker containers are stopped

**Comment by sarim** [comment]
> I was finally able to reproduce the issue

how did you manage to reproduce? For ref I'm running Ubuntu 22.04 x86_64 in WSL2.
<details>

<summary>.symfony.local.yaml</summary>

```yml
http:
    port: 8005
    daemon: true
    gzip: true

workers:
    # auto start Docker compose when starting server (available since Symfony CLI 5.7.0)
    docker_compose: ~

    messenger_consume_async:
        cmd: ["symfony", "console", "messenger:consume", "async", "-vv"]
        watch: ["config", "src", "templates", "vendor"]

    vite:
        cmd: ["yarn", "dev"]

```

</details>
 
 For me server:stop always stops all processes (docker and others) instantly.
 
 It might be a good idea to use a process management library in symfony-cli in the future for proper cross-platform process management.
