### ISSUE TITLE
Worker npm_encore_watch watch a file

### ISSUE THREAD

**Issue by ellmout** [symfony-cli/symfony-cli#407]
Hi,

When working with ``npx encore dev --watch`` as a worker, when you change ``webpack.config.js``, you have to restart the worker.

So i config my worker as this :

```yaml
  npm_encore_watch:
     cmd: ['npx', 'encore', 'dev', '--watch']
     watch: ['webpack.config.js']
```

To watch for modification of ``webpack.config.js`` and restart the worker when i update it.

But it doesn't work !

I have a worker for messenger : 

```yaml
  messenger_consume_async:
     cmd: ['symfony', 'console', 'messenger:consume', 'async']
     watch: ['config', 'src', 'templates', 'vendor']
```

It works great but only watch dir !

Thx

**Comment by sarim** [comment]
I guess it's another macos specific issue? It works in my ubuntu.

Off topic: Interesting that webpack itself doesn't reload itself. As webpack is running in watch mode. (I personally use vite, which actually reload on config change).

**Comment by ellmout** [comment]
hi,
i'm on macOs, using phpstorm !

**Comment by tucksaun** [comment]
well works for me, I don't really see what could cause your issue 🤷

**Comment by tucksaun** [comment]
oh except maybe something (just seen that before closing the IDE): you might have autosave enabled and so the reload already happened before you actually hit "Save" ?

**Comment by tucksaun** [comment]
other hypothesis: maybe your file is not on an actual macOS filesystem (samba share, NFS mount, this kind of things) which might not work with FS change notifications?

**Comment by ellmout** [comment]
I'm working in my home folder.
I'm making some test this morning

**Comment by ellmout** [comment]
Juste made some test, i set log level to 4 to see debug info and got :
<img width="624" alt="image" src="https://github.com/symfony-cli/symfony-cli/assets/4562782/e4bd23e2-c508-462b-bf9e-110438f91789">

But i think the cli can't restart npm watch because of https://github.com/symfony-cli/symfony-cli/issues/402

**Comment by ellmout** [comment]
i confirm it's related to https://github.com/symfony-cli/symfony-cli/issues/402
when i run ``npm run watch``, i can't kill it with ``kill -2`` or ``kill -15``, it works with ``kill -9`` but it leaves a ``webpack`` process running.
i replace ``npm run watch`` with 
```yaml
  npm_encore_watch:
    cmd: [ 'node_modules/@symfony/webpack-encore/bin/encore.js', 'dev', '--watch']
    watch: [ 'webpack.config.js' ]
```
and it's working great !
i will keep it like this for the moment
