### ISSUE TITLE
The "tcp" fix breaks exporting env vars from docker containers with deviating ports

### ISSUE THREAD

**Issue by deZinc** [symfony-cli/symfony-cli#508]
I'm talking about this fix:
https://github.com/symfony-cli/symfony-cli/pull/505/files

I have a pretty straight forward docker-compose.yaml file with this container:
```
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.8.1}
    environment:
      # You should definitely change the master key in production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-fooBarKey}
    volumes:
      - meilisearch_data:/meili_data
    ports:
      - "7700"
 ```
This worked perfectly until I upgrade the symfony cli to the latest version, now, if I run symfony var:export I get
```
export MEILISEARCH_HOST=127.0.0.1
export MEILISEARCH_IP=127.0.0.1
export MEILISEARCH_PORT=58882
export MEILISEARCH_SCHEME=tcp
export MEILISEARCH_URL=tcp://127.0.0.1:58882
```
Where tcp needs to remain http, as it did in the previous versions of symfony cli.

**Comment by mwansinck** [comment]
Here is a workaround to trick Symfony CLI to use an HTTP port

```
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.8.1}
    environment:
      # You should definitely change the master key in production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-fooBarKey}
      MEILI_HTTP_ADDR: "0.0.0.0:8080"
    volumes:
      - meilisearch_data:/meili_data
    ports:
      - "8080"
```

Running symfony var:export shows the correct scheme now

```
export MEILISEARCH_HOST=127.0.0.1
export MEILISEARCH_IP=127.0.0.1
export MEILISEARCH_PORT=59484
export MEILISEARCH_SCHEME=http
export MEILISEARCH_SERVER=http://127.0.0.1:59484
```

Could work for any docker container that is using a non default HTTP port, and where te port of the running service within the container is configurable
