### ISSUE TITLE
Add `local:proxy:target:attach` for external targets

### ISSUE THREAD

**Issue by DracoBlue** [symfony-cli/symfony-cli#510]
Currently we can attach domains like this:

```
symfony local:proxy:domain:attach example
```

and it will make https://example.wip redirect traffic to this.

In some of our projects we have the need to mount a subpath from an external system, e.g.:

* `https://example.wip` should be our php application
* calls to `https://example.wip/api/` are a different application hosted at `https://example.org/api`

My proposal would be to add it like this, to stay compatible to the current implementation.

Add for .symfony.local.yaml like this:

```
proxy:
    domains:
        - example
    targets:
        - domain: example
           basePath: /api
           origin: https://example.org/api
```

and make a cli command for the same result like this:

```
symfony local:proxy:target:attach example --basePath /api --origin https://example.org/api
```

So all requests to `https://example.wip` will be handled by the app and all requests to `https://example.wip/api/*` will be forwarded and returned by `https://example.org/api/*` without the client noticing.

Similiar to #509 and trying to resolve the need from #335
