### ISSUE TITLE
Worker never start when command is run in Makefile or Taskfile

### ISSUE THREAD

**Issue by amenophis** [symfony-cli/symfony-cli#533]
Hello,
I use the following configuration:
```yaml
workers:
    messenger_consume_async:
        cmd: ['symfony', 'console', 'messenger:consume', 'command_outbox', 'command_async']
        watch: ['config', 'src', 'vendor']
```

The `messenger_consume_async` never start if the command `symfony server:start -d` is run from a Makefile or Taskfile.

Logs when command is run with Task:
```
Local Web Server
    Listening on https://127.0.0.1:8000
    The Web server is using PHP FPM 8.3.12 (from default version in $PATH)

Local Domains
    https://my-app.wip

Workers
    PID 58084: /opt/homebrew/Cellar/php/8.3.12/sbin/php-fpm --nodaemonize --fpm-config /Users/jeremyleherpeur/.symfony5/php/9f463328ea6a764805a5016f7899e2b764294579/fpm-8.3.12.ini --force-stderr

Environment Variables
    Exposed from Docker
```

Logs when command is run directly:
```
Local Web Server
    Listening on https://127.0.0.1:8000
    The Web server is using PHP FPM 8.3.12 (from default version in $PATH)

Local Domains
    https://my-app.wip

Workers
    PID 59906: /opt/homebrew/Cellar/php/8.3.12/sbin/php-fpm --nodaemonize --fpm-config /Users/jeremyleherpeur/.symfony5/php/9f463328ea6a764805a5016f7899e2b764294579/fpm-8.3.12.ini --force-stderr
    PID 60009: symfony console messenger:consume command_outbox command_async (watching config/, src/, vendor/)

Environment Variables
    Exposed from Docker
```

Do you have an idea why ?

Thanks 🙏
