### ISSUE TITLE
DNS Issue when running messenger consume workers using symfony-cli

### ISSUE THREAD

**Issue by amenophis** [symfony-cli/symfony-cli#534]
Hello 👋 

I am trying to use symfony cli workers to run my symfony messenger consume commands locally.
Some on my messenger handler use symfony/http-client to make external call, but none of them work because of DNS issue.
When I run manually the consume commands from my terminal, it works without issues.

Do you have an idea why ?

Thanks 🙏

**Comment by amenophis** [comment]
I found a workaround to make it work.

My current config is this one (not working)
```yaml
workers:
    docker_compose: ~
    messenger_consume_command_outbox:
        cmd: ['symfony', 'console', 'messenger:consume', 'command_outbox']
        watch: ['config', 'src', 'vendor']
    messenger_consume_command_async:
        cmd: ['symfony', 'console', 'messenger:consume', 'command_async']
        watch: ['config', 'src', 'vendor']
```

It work if I replace `cmd: ['symfony', 'console', ...]` by `cmd: ['bin/console', ...]`

Any idea why using `symfony console` didn't work ?
