### ISSUE TITLE
Make the Mercure scheme dynamic.

### ISSUE THREAD

**Issue by seb-jean** [symfony-cli/symfony-cli#598]
Hello :),

I'd like to use Mercure with an "https" scheme. But I see that in the envs/docker.go file, it's "http". Is there a way to make this dynamic?

Thanks :)

https://github.com/symfony-cli/symfony-cli/blob/af6f6b7912bc7987e185035f723e3aaa633edfea/envs/docker.go#L445-L454

**Comment by seb-jean** [comment]
Indeed, why not expose parts of the URL 😊.

**Comment by seb-jean** [comment]
I'll add more context for better understanding :).
1. I'm in a local environment, with Docker, Symfony 7.2.5, Mercure, and Symfony CLI.
2. I ran the command `symfony server:ca:install` to use HTTPS locally.
3. I accessed my website with the URL https://127.0.0.1:8000
4. I got an error: `Access to resource at 'http://127.0.0.1:58290/.well-known/mercure?topic=notifications_1CNJAXZK51rBs7Cp6tLrrJ' from origin 'https://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I then changed the value of cors_origins and uncommented `SERVER_NAME` in `compose.yaml`:

```yaml
# compose.yaml

services:
  mercure:
    environment:
      #SERVER_NAME: ':80'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
```

to
```yaml
# compose.yaml
  mercure:
    environment:
      SERVER_NAME: ':80'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://127.0.0.1:8000
```

5. The error regarding CORS policy is no longer present.
6.  I'm using `turbo_stream_listen("topics", "default", { subscribe: 'topics', withCredentials: true }}` which calls `mercure()` Twig function.
7. The `mercureAuthorization` cookie is created correctly.
8. The publish is done correctly; I can see it in the Mercure tab of the Symfony profiler.
9. I launch another browser to view the subscription. The subscription is not successful; I don't receive anything.
10. I think the problem is that I'm on https://127.0.0.1:8000 (HTTPS) and Mercure is listening on http://127.0.0.1:58290/.well-known/mercure?topic=notifications_1CNJAXZK51rBs7Cp6tLrrJ (HTTP).
11. I tried modifying `MERCURE_URL`, but that doesn't work either.

Is there a configuration I did wrong? Is this normal?
I have no interest in having the Mercure URL in HTTPS on a development environment.

Thanks :).
